### ISSUE TITLE
Options hash not passed to Poltergeist driver

### ISSUE THREAD

**Issue by asehra** [Ladtech/page_magic#16]
Options passed to [`PageMagic.session`](https://github.com/Ladtech/page_magic/blob/master/lib/page_magic.rb#L22) method are not passed down to Poltergeist driver. This is limiting our capabilities of configuring the browser.

**Comment by lashd** [comment]
version 0.11.0.alpha7 has now been released. This has an interface breaking change to the session method that now requires named parameter for browser

e.g. `PageMagic.session(browser: :chrome)`
